version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - govet
    - errcheck
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - durationcheck
    - errchkjson
    - errorlint
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - loggercheck
    - makezero
    - misspell
    - nilnesserr
    - protogetter
    - revive
    - spancheck
    - staticcheck
    - testifylint
    - unconvert
    - zerologlint
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -QF*
        - -ST1003
        - -ST1016
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    gocritic:
      disabled-checks:
        - appendAssign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .github
      - scripts
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - .github
      - scripts
      - coerce.go
