#/bin/sh


cat >doc.go <<'EOF'
// Code generated by doc_gen.sh; DO NOT EDIT.

// Command oj allows to filter JSON files.
/*
EOF

go run main.go -help 2>&1 | grep -v 'exit status' >>doc.go

cat >>doc.go <<'EOF'
*/
package main
EOF
